baseurl: http://plugins.drone.io/
title: Plugins | Drone
theme: drone-hugo-theme

copyright: Copyright © 2016 Drone.IO Inc.

params:
  heading: Plugins
  tagline: >
    Browse our registry of community plugins to customize
    your continuous delivery pipeline.
  search: Search Plugins

menu:
  main:
    - identifier: documentation
      weight: 1
      name: Documentation
      url: http://readme.drone.io/
    - identifier: tutorial
      weight: 2
      name: Tutorials
      url: http://readme.drone.io/tutorials/
    - identifier: question
      weight: 3
      name: Questions
      url: http://readme.drone.io/questions/
    - identifier: plugin
      weight: 4
      name: Plugins
      url: /

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

languages:
  en:
    weight: 1
    languageName: English

  fr:
    weight: 2
    languageName: Français
    heading: Plugins
    tagline: >
      Browse our registry of community plugins to customize
      your continuous delivery pipeline.
    search: Recherche
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: Documentation
          url: http://readme.drone.io/fr/
        - identifier: tutorial
          weight: 2
          name: Tutoriels
          url: http://readme.drone.io/fr/tutorials/
        - identifier: question
          weight: 3
          name: Questions
          url: http://readme.drone.io/fr/questions/
        - identifier: plugin
          weight: 4
          name: Plugins
          url: /fr/

  es:
    weight: 3
    languageName: Español
    heading: Plugins
    tagline: >
      Browse our registry of community plugins to customize
      your continuous delivery pipeline.
    search: Buscar
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: Documentación
          url: http://readme.drone.io/es/
        - identifier: tutorial
          weight: 2
          name: Tutoriales
          url: http://readme.drone.io/es/tutorials/
        - identifier: question
          weight: 3
          name: Preguntas
          url: http://readme.drone.io/es/questions/
        - identifier: plugin
          weight: 4
          name: Plugins
          url: /es/

  it:
    weight: 4
    languageName: Italiano
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: Documentazione
          url: http://readme.drone.io/it/
        - identifier: tutorial
          weight: 2
          name: Tutorial
          url: http://readme.drone.io/it/tutorials/
        - identifier: question
          weight: 3
          name: Domande
          url: http://readme.drone.io/it/questions/
        - identifier: plugin
          weight: 4
          name: Plugins
          url: /it/

  pt:
    weight: 5
    languageName: Português
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: Documentação
          url: http://readme.drone.io/pt/
        - identifier: tutorial
          weight: 2
          name: Tutoriais
          url: http://readme.drone.io/pt/tutorials/
        - identifier: question
          weight: 3
          name: Preguntas
          url: http://readme.drone.io/pt/questions/
        - identifier: plugin
          weight: 4
          name: Plugins
          url: /pt/

  zh-cn:
    weight: 6
    languageName: 中文(简体)
    heading: 插件
    tagline: >
      Browse our registry of community plugins to customize
      your continuous delivery pipeline.
    search: 搜索
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: 文档
          url: http://readme.drone.io/zh-cn/
        - identifier: tutorial
          weight: 2
          name: 教程
          url: http://readme.drone.io/zh-cn/tutorials/
        - identifier: question
          weight: 3
          name: 问题
          url: http://readme.drone.io/zh-cn/questions/
        - identifier: plugin
          weight: 4
          name: 插件
          url: /zh-cn/

  zh-tw:
    weight: 7
    languageName: 中文(台灣)
    heading: 外掛
    tagline: >
      Browse our registry of community plugins to customize
      your continuous delivery pipeline.
    search: 搜索
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: 文件
          url: http://readme.drone.io/zh-tw/
        - identifier: tutorial
          weight: 2
          name: 教學
          url: http://readme.drone.io/zh-tw/tutorials/
        - identifier: question
          weight: 3
          name: 問題
          url: http://readme.drone.io/zh-tw/questions/
        - identifier: plugin
          weight: 4
          name: 外掛
          url: /zh-tw/

  ja:
    weight: 8
    languageName: 日本語
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: ドキュメント
          url: http://readme.drone.io/ja/
        - identifier: tutorial
          weight: 2
          name: チュートリアル
          url: http://readme.drone.io/ja/tutorials/
        - identifier: question
          weight: 3
          name: 質問
          url: http://readme.drone.io/ja/questions/
        - identifier: plugin
          weight: 4
          name: プラグイン
          url: /ja/

  ko:
    weight: 9
    languageName: 한국어
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: 설명서
          url: http://readme.drone.io/en/
        - identifier: tutorial
          weight: 2
          name: 자습서
          url: http://readme.drone.io/en/tutorials/
        - identifier: question
          weight: 3
          name: 질문
          url: http://readme.drone.io/en/questions/
        - identifier: plugin
          weight: 4
          name: 플러그인
          url: /ko/

  ru:
    weight: 9
    languageName: pусский
    menu:
      main:
        - identifier: documentation
          weight: 1
          name: Документация
          url: http://readme.drone.io/ru/
        - identifier: tutorial
          weight: 2
          name: Учебники
          url: http://readme.drone.io/ru/tutorials/
        - identifier: question
          weight: 3
          name: Вопросы
          url: http://readme.drone.io/ru/questions/
        - identifier: plugin
          weight: 4
          name: Плагины
          url: /ru/
